services:
  opengist:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/thomiceli/opengist:${IMAGE_VERSION}
    restart: always
    ports:
      - ${HOST_PORT}:6157
    volumes:
      - ${VOLUMES_PATH}/data:/opengist
    networks:
      - onenet
networks:
  onenet:
    external: true