services:
  homeserver:
    container_name: ${CONDUWUIT_CONTAINER_NAME}
    image: girlbossceo/conduwuit:${CONDUWUIT_IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - ${CONDUWUIT_HOST_PORT}:${CONDUWUIT_PORT}
    volumes:
      - ${CONDUWUIT_VOLUMES_PATH}/db:/var/lib/conduwuit/
    environment:
      - CONDUWUIT_SERVER_NAME=${CONDUWUIT_SERVER_NAME}
      - CONDUWUIT_DATABASE_PATH=${CONDUWUIT_DATABASE_PATH}
      - CONDUWUIT_DATABASE_BACKEND=${CONDUWUIT_DATABASE_BACKEND}
      - CONDUWUIT_PORT=${CONDUWUIT_PORT}
      - CONDUWUIT_MAX_REQUEST_SIZE=${CONDUWUIT_MAX_REQUEST_SIZE}
      - CONDUWUIT_ALLOW_REGISTRATION=${CONDUWUIT_ALLOW_REGISTRATION}
      - CONDUWUIT_REGISTRATION_TOKEN=${CONDUWUIT_REGISTRATION_TOKEN}
      - CONDUWUIT_ALLOW_FEDERATION=${CONDUWUIT_ALLOW_FEDERATION}
      - CONDUWUIT_ALLOW_CHECK_FOR_UPDATES=${CONDUWUIT_ALLOW_CHECK_FOR_UPDATES}
      - CONDUWUIT_TRUSTED_SERVERS=${CONDUWUIT_TRUSTED_SERVERS}
      - CONDUWUIT_ADDRESS=${CONDUWUIT_ADDRESS}
    networks:
      - onenet
  web:
    container_name: ${FLUFFYCHAT_CONTAINER_NAME}
    image: ghcr.io/krille-chan/fluffychat:${FLUFFYCHAT_IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - ${FLUFFYCHAT_HOST_PORT}:80
    networks:
      - onenet
networks:
  onenet:
    external: true