services:
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: docker.io/valkey/valkey:${REDIS_IMAGE_VERSION}
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - onenet
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: ${SEARXNG_CONTAINER_NAME}
    image: docker.io/searxng/searxng:${SEARXNG_IMAGE_VERSION}
    restart: unless-stopped
    networks:
      - onenet
    ports:
      - ${HOST_PORT}:8080
    volumes:
      - ${VOLUMES_PATH}/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  onenet:
    external: true