services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    image: joplin/server:${APP_IMAGE_VERSION}
    depends_on:
      - db
    ports:
      - ${APP_HOST_PORT}:${APP_PORT}
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=${DB_CLIENT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - onenet
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:${DB_IMAGE_VERSION}
    volumes:
      - ${VOLUMES_PATH}/data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - onenet
networks:
  onenet:
    external: true