services:
  ddns-go:
    container_name: ${CONTAINER_NAME}
    image: jeessy/ddns-go:${IMAGE_VERSION}
    restart: always
    ports:
      - ${HOST_PORT}:9876
    volumes:
      - ${VOLUMES_PATH}/data:/root
    networks:
      - onenet
networks:
  onenet:
    external: true